spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tN4uLwF9pjE7auo88gL
      secret-key: e08QzSMH96rDAUFkMySMTCEgcY8BpR
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: guli-mall-lxy

  application:
    name: gulimall-third-party

server:
  port: 30000
